### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by KovalevArtem** [ChrisAnd1998/FalconX-Center-Taskbar#18] opened 2019-08-14 21:15 UTC
I am saddened that the program is in English only.
I suggest to localize the program.
I am ready to assist in the translation into Russian.
(For example, you can use the service Crowdin or any other. Crowdin is free for Open source projects.)

**Comment by user00101010** [comment] 2019-09-10 06:46
If Chris decides to go through with this, keep me posted as I can help with my local translations. However as the options aren't that many at all, and it's a "out of your way" application, personally I'm not very sure how beneficial this is (then again, English is not an issue for me).

**Comment by ChrisAnd1998** [comment] 2019-09-30 13:39
The idea is very good and probably needed for some people.
I have tried importing some languages but the problem is that every control needs to be resized and repositioned when you change to a different language.

For example:
**animation speed in milliseconds**
_animatiesnelheid in milliseconden
Animationsgeschwindigkeit in Millisekunden
vitesse d'animation en millisecondes
Скорость анимации в миллисекундах
velocidad de animación en milisegundos_

So i now decide to not close it. And keep it for in the future. 
As it requires a lot of work.

**Comment by Lukas34** [comment] 2019-10-30 10:35
I can help with German translations if you want to do this in the future.

**Comment by ChrisAnd1998** [comment] 2019-10-30 11:10
Allright, thanks! i will get in touch with you when i will add this feature :)

**Closed** 2020-03-30 07:37 UTC
Labels: Feature Request ✨, Maybe later 🚫

**Comment by KovalevArtem** [comment] 2020-03-30 10:32
Will there be no translation?

**Comment by ChrisAnd1998** [comment] 2020-03-30 10:36
There will be but, probably not for a while. I am trying to clean up the issues and only keep the important ones. I will reopen the issue when FalconX is ready for it ;)

**Comment by KovalevArtem** [comment] 2020-09-22 21:00
@ChrisAnd1998 Perhaps it's time to reopen the issue?
