### ISSUE TITLE
!!Index was outside the bounds of the array

### ISSUE THREAD

**Issue by watermarkhu** [ChrisAnd1998/FalconX-Center-Taskbar#173] opened 2020-02-20 12:40 UTC
Starting today or yesterday, I'm seeing this message every time I restart my computer, and the taskbar is not centered. 
![image](https://user-images.githubusercontent.com/18556882/74934345-4bf2ac80-53e6-11ea-9434-dbe0695a4a2d.png)
Opening the FalconX settings app and restarting the service throws the same error message but centers the taskbar. 
Seeing this on both of my machines.

**Comment by ChrisAnd1998** [comment] 2020-02-20 16:12
My bad! I forgot to take it out for release. This will be fixed next update!
![Untitddled](https://user-images.githubusercontent.com/50437199/74954863-10ff7180-5404-11ea-99af-ab479861d144.png)

**Comment by Talisman39ar** [comment] 2020-02-20 21:45
Got this also when I had to restart my machine. At the same time, my Start menu, Start button, and Windows Settings all stopped working. Coincidence? I had to go through and rebuild the Start menu as described here https://mspoweruser.com/solution-start-menu-not-working-windows-10/ - it's now working but has been reset to default so I have to do everything over again to organize it. No other system updates have been done recently.

**Comment by ChrisAnd1998** [comment] 2020-02-20 21:55
@Talisman39ar Must be a coincidence. FalconX gets the taskbar icons with the UI Automation API by Microsoft and moves it after all the calculations are made. So the taskbar is controlled from outside the explorer. Not by dll injections or changing the registry. So i think you did actually encounter a bug in Windows 10 not necessarily caused by FalconX.

**Closed** 2020-02-23 08:05 UTC
Labels: For next Update ✔️, Little mistake
