### ISSUE TITLE
Settings reset after automatic restart on monitor disconnect

### ISSUE THREAD

**Issue by swsegdan** [ChrisAnd1998/FalconX-Center-Taskbar#116] opened 2019-12-17 07:44 UTC
When the automatic restart triggers after a monitor is disconnected/connected taskbar styling is disabled, the easing is reset to the default one and "Run at Startup" is unchecked.

**Comment by Cabola** [comment] 2019-12-20 04:47
Yup I can confirm this, it just happened to me too..

**Comment by apolios** [comment] 2019-12-21 08:29
I can add that when change monitor, Run at startup is off and Taskbar style options is unchecked.
Centering works ok now.

**Comment by ericpa06** [comment] 2019-12-24 05:12
I'm also experiencing this bug, just for the records.

**Comment by user00101010** [comment] 2019-12-25 08:54
I can confirm this bug as well. It is only present on version 1.3.5.0 (both Windows Store and regular version). On 1.3.4.0 everything is working as expected.

It actually ocurrs with any display change. I have two monitors and a TV connected and changing between single/extend/clone resets the taskbar styling options.

**Comment by samirklahaine** [comment] 2019-12-25 08:54
i also have the same issue the task style option is disabled every time i run a game in a different resolusion tham my desktop, every time i turn off my screen or start/restart my pc.

can you fix that please ?

**Comment by fvknl** [comment] 2020-01-14 06:42
Can confirm I also have this issue, and as @samirklahaine mentioned when running games or anything that resets the resolution of the monitor the issues arises.

Is this issue new? I don't recall having it.

**Comment by user00101010** [comment] 2020-01-16 10:59
Can confirm the issue persists on version 1.3.8.0.

Yeah the issue is new @fvknl As I mentioned, use version 1.3.4.0 for now in order to avoid it.

**Comment by ChrisAnd1998** [comment] 2020-01-19 15:30
Does this still happen in 1.3.9.0?

**Comment by user00101010** [comment] 2020-01-19 17:31
I can confirm the issue seems to be resolved in1.3.9.0! Thank you very much @ChrisAnd1998 !

**Comment by ChrisAnd1998** [comment] 2020-01-19 21:47
@user00101010 Nice! 😁

**Closed by ChrisAnd1998** 2020-01-19 21:47 UTC
Labels: Possible bug needs reproduce 🕵️
