### ISSUE TITLE
Taskbar icons continuously moving

### ISSUE THREAD

**Issue by logicb0mb** [ChrisAnd1998/FalconX-Center-Taskbar#30] opened 2019-10-15 14:48 UTC
In Windows 10 1903, Build version: 18362.418, taskbar icons which are centered are not fixed on a single position, instead they are continuously, performing an oscillatory motion.

**Comment by ChrisAnd1998** [comment] 2019-10-15 17:05
Hmm, here are the previous builds of FalconX. Can you see which update doesn't give you this issue
starting from update 1.2.0.0 and up?

https://chrisandriessen.nl/web/downloads/falconx/

**Comment by golu0305** [comment] 2019-10-18 14:26
Same issues although it happens sometimes but its is very annoying , currently on the latest build

**Comment by ChrisAnd1998** [comment] 2019-10-18 14:35
Like a it's wiggeling a little bit or moving with big steps?

**Comment by JAGERMeisterPC** [comment] 2019-10-18 14:48
It's wiggeling

**Comment by ChrisAnd1998** [comment] 2019-10-18 17:02
Allright thanks, i will try to fix it.

**Comment by ChrisAnd1998** [comment] 2019-10-18 17:50
How about 1.2.7.0 ? (just released)

**Comment by shreyasshukla16** [comment] 2019-10-18 18:12
Will notify you after using it for a while!

**Comment by JAGERMeisterPC** [comment] 2019-10-18 18:38
Using 1.2.7.0 and yes the icons still wiggles when opening and closing an   app , and sometimes just randomly .  and in this update i don't know why the animations start a little when a new app is opened

**Comment by djsime1** [comment] 2019-10-19 19:17
Version 1.2.7.0 still has this effect. It only happens when the available space increased. (Closing a window or hiding a taskbar icon.) It usually lasts 3-7 seconds. I've tested this with multiple animations and most of them wiggle like this.
https://upload.dj.je/falconx.mp4

**Comment by ChrisAnd1998** [comment] 2019-10-19 19:21
Well, i have almost completely rewritten FalconX today to keep the best and write better code.
Can you see if it's fixed in this testing version?
https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

**Comment by djsime1** [comment] 2019-10-19 19:28
Sadly it still seems to be shaking. The animation I used in this and the previous video are QuintOut with 200ms animation time.
https://upload.dj.je/falconx2.mp4

**Comment by ChrisAnd1998** [comment] 2019-10-19 19:30
Does it also happen with the other animations?

**Comment by djsime1** [comment] 2019-10-19 19:50
I decided to test both versions on my other laptop and noticed no shaking with any of the animations. On my main laptop, I'm noticing the shaking with Quint, Expo, and Circ.

**Comment by ChrisAnd1998** [comment] 2019-10-19 19:52
Allright, thanks for testing 😁. I will try to look into those animations tomorrow to see if i can find anything.

**Comment by djsime1** [comment] 2019-10-19 19:55
You're welcome. Thanks for keeping up this project.

**Comment by JAGERMeisterPC** [comment] 2019-10-27 18:41
the latest build still has the icons shaking, and also the animations doesn't seem smooth as comapared to the previous versions

**Comment by reihwald** [comment] 2019-10-30 19:12
For me the icons are always jumping around (a few pixels) when I have 2 icons on the taskbar, no matter what. But I have a bigger amounts of icons, it only happens when I remove an icon (I have no icons fixed so if I close a window) and there are an even amount of icons left. It doesn't happen when I go from 3 to 4 for example

**Comment by ChrisAnd1998** [comment] 2019-10-30 19:29
Thanks! i am working on it.

**Comment by JAGERMeisterPC** [comment] 2019-10-31 10:37
hey chris,
I have been trying the testing version  and the shaking only happened once or twice and till now i cannot see any shaking , but the animations are getting triggered twice

**Comment by JAGERMeisterPC** [comment] 2019-10-31 10:41
hey chris,
I have been trying the testing version and it still shakes but stops after 5-7 seconds after an app is been closed but the animations are getting triggered twice

**Comment by ChrisAnd1998** [comment] 2019-10-31 11:03
Allright, thanks!

**Comment by CarnageMarkus** [comment] 2019-11-11 09:49
Hi, I got the same problem, with taskbar shifting left and right. Here is video: https://www.youtube.com/watch?v=58gSNOJvLA0&feature=youtu.be

I noticed, it happens only if items count is multiple of 2 (2,4,8...) - shown in video.
But as the app count increases, the shifting almost disappears (visible jiggle upon opening 4th, 8th app).
Also, I noticed it seems to happen only on my MacBook with windows bootcamp (2880x1800). It doesn't seem to happen at desktop PC, both of which have quite large resolution (3440x1440).

My quess would be there is some floating-point calculation happening and/or animation easing that is rounded differently every step ? Or maybe just the animation easing gets caught in loop where it overslides then tries to come back and gets caught in infinite loop... Maybe I can investigate more, but don't have time as of now.

Hope this helps fining the issue.

**Comment by ChrisAnd1998** [comment] 2019-11-11 10:48
Thanks! this helps me alot :) i need as much information as possible about this bug to be able to fix it. Also thanks for the suggestion i will be looking into it when i get back home.

**Comment by ChrisAnd1998** [comment] 2019-11-11 14:35
Can you see if this testing build fixes the issue?
I am also gonna look into your suggestion. For if the issue still persists.

https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

**Comment by CarnageMarkus** [comment] 2019-11-11 14:44
Tested, didn't help.  😢

**Comment by ChrisAnd1998** [comment] 2019-11-11 15:09
Hmm, Thanks for testing :) i'll dig deeper into this and your suggestion for a possible solution.

Can you tell me if your on Intel or AMD? I am asking this because, my current PC and testing PC's are all based on Intel running different builds of Windows 10 and can't reproduce this issue. 
Maybe that can explain why FalconX behaves differently for some people.

**Comment by CarnageMarkus** [comment] 2019-11-11 15:45
I am running Intel i4770HQ, AMD at home, which doesn't seem to have that issue. Maybe you can make some build with simple logging, so we could see calculations ? Since I can reproduce this issue without problem, you could get data you need...

**Comment by ChrisAnd1998** [comment] 2019-11-11 16:09
Allright, i will make a simple output logger. I will get back to you when its ready :)

**Comment by BeardedOranges** [comment] 2019-11-12 15:44
I also seem to have this issue. I also noticed like Carnage said that it only happens on multiples of 2. For reference, I am on a 1080p laptop with an i7 8750h. I also have the linear transition, and it also has the same issue for the "none" transition. I am also willing to help with the output logger thing

**Comment by ChrisAnd1998** [comment] 2019-11-12 16:26
Thanks BeardedOranges, for letting me know :) The "Output logger" is already ready.

**Comment by ChrisAnd1998** [comment] 2019-11-12 16:27
I have uploaded a new testing build v2. You can run FalconX by using "FalconXOutput.exe".

https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

**Comment by BeardedOranges** [comment] 2019-11-12 17:06
I got it to reproduce when it was at 4 icons. It actually took awhile to reproduce, I thought somehow it magically fixed, but then it did the jittering thing and the log reflected all the changes. It seems to be moving from one pixel back and forth. You have to scroll down a bit, I went up to I think 6 icons, then back down to 4 and thats when it started.
[OutputLog.txt](https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/files/3837317/OutputLog.txt)

**Comment by ChrisAnd1998** [comment] 2019-11-12 17:49
Hmm, Interesting. I can see it's constantly allowing to move the taskbar and it moves by 1 pixel as you said. It also never stopped doing it.

I will make it output some more information so we can point out where the issue is exactly.
I will respond back in a couple minutes for a new testing build.

**Comment by ChrisAnd1998** [comment] 2019-11-12 18:14
Allright, here is v3.

https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

**Comment by BeardedOranges** [comment] 2019-11-12 20:01
Ok, here is the new log, luckily it is doing the jittering again so we should get some good data. 
[Output2.txt](https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/files/3837988/Output2.txt)

**Comment by ChrisAnd1998** [comment] 2019-11-12 20:34
The first check constantly passes you to the calculation because, its 1 pixel off everytime.
The call to the animator also passes because it's also 1 pixel off what means it's different. 
Resulting in a loop moving the taskbar.

So what i did now is made some safety checks allowing only differences bigger than 5 pixels to pass.

https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

**Comment by CarnageMarkus** [comment] 2019-11-13 08:30
![image](https://user-images.githubusercontent.com/9625437/68746019-f5f8b680-05f7-11ea-8d44-1099c46bd9bc.png)

Trying latest build seems to solve the issue. It stops updating even though its 1 pixel off. Any idea why its pixel off every time ?

**Comment by ChrisAnd1998** [comment] 2019-11-13 09:11
I have no idea because, it doesn't happen on my side. I will have to investigate that further.

**Comment by ChrisAnd1998** [comment] 2019-11-13 16:29
So the Safety Check works but, it doesn't feel like a proper fix.
What i've done now is disabled the Safety Checks and made the Animators round to integers instead of doubles. For me it still works nicely and it even feels like the animations got smoother.

https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing <-- v5

Let me know.

**Comment by BeardedOranges** [comment] 2019-11-14 01:39
Alright ill test it out and get back to you

**Comment by BeardedOranges** [comment] 2019-11-14 01:49
Alright, so it still happens somehow, here is the new output. I almost said it worked, because it only started doing that like the third time I tested it at four icons. Here is the log
[Output3.txt](https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/files/3844236/Output3.txt)

**Comment by ChrisAnd1998** [comment] 2019-11-14 06:00
Thanks for testing it again 😁. 
What animation are you using?

**Comment by ChrisAnd1998** [comment] 2019-11-14 06:50
v6 will fix the taskbars position when the animator has finished animating.
https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing <-- v6

**Comment by BeardedOranges** [comment] 2019-11-15 22:26
Yeah im confused, it is still happening. I use have tried multiple animations, but during those logs it was set to Linear

**Comment by ChrisAnd1998** [comment] 2019-11-16 05:56
This is weird but, I'll keep trying 😉. Can i have your output again?

**Comment by c-m-4** [comment] 2019-11-18 20:11
@ChrisAnd1998 I think I found out the issue. It has to do with Windows scaling. Some computers are scaling at 150%. I've noticed when I change it to 100% it stops twitching. Once I did that I switched it back to 150% scaling and no more twitching, although some of the features such as transparency aren't working. I hope this helped as I created an account just to comment this. Great application. Would love to see it stay updated.

**Comment by BeardedOranges** [comment] 2019-11-20 02:54
Ok I noticed something too. It only twitches for me when I have it set to the recommended setting (which is 125%). Both 100% and 150% didn't have the jittering, only problem is that 150 is much to big and 100 is pretty small at least for my display. Hope this helps!

**Comment by c-m-4** [comment] 2019-11-20 18:24
@BeardedOranges I actually meant to say 125% scaling. Sounds like we're having the same problem.

**Comment by ChrisAnd1998** [comment] 2019-11-20 20:06
Intresting, i will do some testing when i get some te :)

**Comment by digilocker** [comment] 2019-11-30 10:19
Just another to to confirm I'm currently getting this issue.  Running 3440x1440p & 1920x1080 panels at 100% scaling (if that helps).  Interestingly just checked my second monitor and moved a window across and it stopped.  

Just a quick word of thanks for bringing this app out as well Chris, solved a long time problem I've had using an ultrawide monitor!  Look forward to seeing more from it :)

**Comment by ChrisAnd1998** [comment] 2019-11-30 10:23
Thanks @digilocker :)

Can you see if this testing build fixes it?
https://chrisandriessen.nl/web/downloads/falconx/Testing/Release.zip

**Comment by ChrisAnd1998** [comment] 2019-12-01 16:25
It seems to be fixed now. I have done a lot of testing with my DPI @ 125%.
Version 1.3.3.0 contains the fix.

**Closed by ChrisAnd1998** 2019-12-01 16:25 UTC
Labels: Might be a bug (not found a way to reproduce this)

**Comment by BeardedOranges** [comment] 2020-01-22 03:34
Sorry for the super late response. I haven't had any issues since, thanks!

**Comment by ChrisAnd1998** [comment] 2020-01-22 05:59
@BeardedOranges No problem, thanks :)

**Comment by pbarrebenta** [comment] 2022-12-18 06:19
i'm having the same issue no fix yet, on the latest build, it keeps moving untill its completly gone 
![image](https://user-images.githubusercontent.com/119696372/208284515-46870824-bb3a-42ea-aa23-51ea668c1372.png)
