### ISSUE TITLE
Centering doesn't work at startup on two screen setup. 

### ISSUE THREAD

**Issue by Natsyu** [ChrisAnd1998/FalconX-Center-Taskbar#52] opened 2019-10-28 17:33 UTC
After launch I have to move an app window so there is something on both screens, then icons on the taskbar are centralized. After doing so I can close or move that app window back to my main screen.

Version: 27.10.2019 - 1.2.9.0

**Comment by ChrisAnd1998** [comment] 2019-10-29 06:49
Hmm, allright. I cant reproduce this behaivor but, i will add an extra Call to update the taskbar at startup for the next update.

**Comment by ChrisAnd1998** [comment] 2019-11-12 15:43
Can you see if this issue is fixed in the latest update?

**Comment by Natsyu** [comment] 2019-11-12 18:52
The problem still occurs.
Also on a different setup - laptop with 2 screens, all fhd, I have to move apps so every screen contains at least one application.


I recorded a video with this problem.
https://youtu.be/aj4PueqkmFo

Version: 10.11.2019 - 1.3.1.0

**Comment by ChrisAnd1998** [comment] 2019-11-12 19:28
Thanks for your response and video. I will investigate this further tomorrow :)

**Comment by ChrisAnd1998** [comment] 2020-01-19 10:17
Confirmed in issue #91

**Closed by ChrisAnd1998** 2020-01-19 10:17 UTC
Labels: Might be a bug not found a way to reproduce ⚠️
